export {
  GridExtraColumnMenu as GridColumnMenu,
  GRID_COLUMN_MENU_SLOTS_EXTRA as GRID_COLUMN_MENU_SLOTS,
  GRID_COLUMN_MENU_SLOT_PROPS_EXTRA as GRID_COLUMN_MENU_SLOT_PROPS,
} from './GridExtraColumnMenu';
